version: "3.7"

services:
    db:
        container_name: lurker_db
        image: postgres:16
        volumes:
            - postgres_data:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: lurker
            POSTGRES_USER: lurker
            POSTGRES_PASSWORD: ODU1ODlmYWE0MzkzZGRhMGU1MTllYTVl
        healthcheck:
            test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "lurker"]
            timeout: 5s
            interval: 30s
            retries: 3
        networks:
            main:
                aliases:
                    - db

    pgweb:
        container_name: lurker_pgweb
        restart: always
        image: sosedoff/pgweb
        entrypoint:
            ["/usr/bin/pgweb", "--bind=0.0.0.0", "--listen=8081", "--readonly"]
        healthcheck:
            test: ["CMD", "nc", "-vz", "127.0.0.1", "8081"]
            interval: 5s
        ports:
            - "8678:8081"
        environment:
            PGWEB_DATABASE_URL: postgresql://lurker:ODU1ODlmYWE0MzkzZGRhMGU1MTllYTVl@db/lurker?sslmode=disable
        networks:
            - main
        depends_on:
            db:
                condition: service_healthy

    lurker:
        container_name: lurker
        build:
            context: "."
        restart: unless-stopped
        environment:
            DATABASE_URL: postgresql://lurker:ODU1ODlmYWE0MzkzZGRhMGU1MTllYTVl@db/lurker
        volumes:
            - "./config.json:/app/config.json:ro"
        networks:
            - main
        depends_on:
            db:
                condition: service_healthy

volumes:
    postgres_data:

networks:
    main:
